# Author    : Ranjit Kumar Swain
# Web       : www.ranjitswain.com
# YouTube   : https://www.youtube.com/c/ranjitswain
# GitHub    : https://github.com/ranjit4github
########################################################

---
 - hosts: lampserver
   become: true
   vars:
     mysql_root_password: "Sunday@2023"
   tasks:
     - name: Install Apache
       ansible.builtin.yum: name=httpd state=present update_cache=yes

     - name: Install PHP
       ansible.builtin.yum : name={{item}} state=present update_cache=yes
       with_items:
            - php
            - php-mysql
         
     - name: Start Apache Server
       service:
         name: httpd
         enabled: true
         state: started
         
     - name: Download Mariadb repo
       ansible.builtin.get_url:
         url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
         dest: /home/ec2-user/mariadb_repo_setup
         
     - name: Setup mariadb version to 10.7
       ansible.builtin.command:
         cmd: bash mariadb_repo_setup --os-type=rhel --os-version=7 --mariadb-server-version=10.7
       become: yes
       become_user: root
       
     - name: Remove cache
       ansible.builtin.command:
         cmd: rm -rf /var/cache/yum
       become: yes
       become_user: root
       
     - name: Install Mariadb
       ansible.builtin.yum: name={{item}} state=present update_cache=yes
       with_items:
            - MariaDB-server
            - MariaDB-client         
       become: yes
       become_user: root
       
     - name: Copy db dump file
       ansible.builtin.copy:
         src: dump.sql
         dest: /tmp
     - name: Start MariaDB
       service:
         name: mariadb
         enabled: true
         state: started
         
     - name: Install dependency for mysql_db module
       ansible.builtin.yum: name=MySQL-python state=present
       
     - name: mysql root password
       community.mysql.mysql_user:
         login_user: root
         login_password: "{{mysql_root_password}}"
         user: root
         check_implicit_admin: true
         password: "{{mysql_root_password}}"
         host: localhost
         
     - name: Create a new database
       community.mysql.mysql_db:
         check_implicit_admin: true
         login_user: root
         login_password: "{{mysql_root_password}}"
         name: mbdatabase
         state: present
         
     - name: Dump database to dump.sql
       community.mysql.mysql_db:
         check_implicit_admin: true
         login_user: root
         login_password: "{{mysql_root_password}}"         
         state: import
         name: mbdatabase
         encoding: latin1
         target: /tmp/dump.sql

     - name: Download phpMyAdmin
       ansible.builtin.get_url:
         url: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
         dest: /var/www/html
         become: true
         become_user: root
        
     - name: Create Directory
       ansible.builtin.file:
         path: /var/www/html/phpMyAdmin
         state: directory
         mode: '0755'
     
     - name: Extract the tar file
       ansible.builtin.command: chdir=/var/www/html /bin/tar xvf /var/www/html/phpMyAdmin-latest-all-languages.tar.gz -C phpMyAdmin creates=phpMyAdmin/phpMyAdmin-latest-all-languages

     - name: Create a symlink
       ansible.builtin.file:
         src: /var/www/html/phpMyAdmin-latest-all-languages
         dest: /var/www/html/phpMyAdmin
         state: link
